// Code generated by sqlc. DO NOT EDIT.
// source: mail_template.sql

package db

import (
	"context"
)

const createMailTemplate = `-- name: CreateMailTemplate :one
INSERT  INTO mail_templates (
 "content", "subject"
) VALUES (
    $1, $2
)
RETURNING id, subject, content, created_at, deleted_at, updated_at
`

type CreateMailTemplateParams struct {
	Content string `json:"content"`
	Subject string `json:"subject"`
}

func (q *Queries) CreateMailTemplate(ctx context.Context, arg CreateMailTemplateParams) (MailTemplate, error) {
	row := q.db.QueryRowContext(ctx, createMailTemplate, arg.Content, arg.Subject)
	var i MailTemplate
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Content,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
