// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type MailTemplate struct {
	ID        int32        `json:"id"`
	Subject   string       `json:"subject"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
