// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: mail_service.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_mail_service_proto protoreflect.FileDescriptor

var file_mail_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x12,
	0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x32, 0x6a, 0x0a, 0x13, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12,
	0x23, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x6d, 0x61, 0x69, 0x6c, 0x2e,
	0x4d, 0x61, 0x69, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x00, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_mail_service_proto_goTypes = []interface{}{
	(*CreateMailTemplateRequest)(nil), // 0: sendmail.CreateMailTemplateRequest
	(*MailTemplate)(nil),              // 1: sendmail.MailTemplate
}
var file_mail_service_proto_depIdxs = []int32{
	0, // 0: sendmail.MailTemplateService.CreateMailTemplate:input_type -> sendmail.CreateMailTemplateRequest
	1, // 1: sendmail.MailTemplateService.CreateMailTemplate:output_type -> sendmail.MailTemplate
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mail_service_proto_init() }
func file_mail_service_proto_init() {
	if File_mail_service_proto != nil {
		return
	}
	file_mail_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mail_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mail_service_proto_goTypes,
		DependencyIndexes: file_mail_service_proto_depIdxs,
	}.Build()
	File_mail_service_proto = out.File
	file_mail_service_proto_rawDesc = nil
	file_mail_service_proto_goTypes = nil
	file_mail_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MailTemplateServiceClient is the client API for MailTemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MailTemplateServiceClient interface {
	CreateMailTemplate(ctx context.Context, in *CreateMailTemplateRequest, opts ...grpc.CallOption) (*MailTemplate, error)
}

type mailTemplateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailTemplateServiceClient(cc grpc.ClientConnInterface) MailTemplateServiceClient {
	return &mailTemplateServiceClient{cc}
}

func (c *mailTemplateServiceClient) CreateMailTemplate(ctx context.Context, in *CreateMailTemplateRequest, opts ...grpc.CallOption) (*MailTemplate, error) {
	out := new(MailTemplate)
	err := c.cc.Invoke(ctx, "/sendmail.MailTemplateService/CreateMailTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailTemplateServiceServer is the server API for MailTemplateService service.
type MailTemplateServiceServer interface {
	CreateMailTemplate(context.Context, *CreateMailTemplateRequest) (*MailTemplate, error)
}

// UnimplementedMailTemplateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMailTemplateServiceServer struct {
}

func (*UnimplementedMailTemplateServiceServer) CreateMailTemplate(context.Context, *CreateMailTemplateRequest) (*MailTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMailTemplate not implemented")
}

func RegisterMailTemplateServiceServer(s *grpc.Server, srv MailTemplateServiceServer) {
	s.RegisterService(&_MailTemplateService_serviceDesc, srv)
}

func _MailTemplateService_CreateMailTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMailTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailTemplateServiceServer).CreateMailTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sendmail.MailTemplateService/CreateMailTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailTemplateServiceServer).CreateMailTemplate(ctx, req.(*CreateMailTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MailTemplateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sendmail.MailTemplateService",
	HandlerType: (*MailTemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMailTemplate",
			Handler:    _MailTemplateService_CreateMailTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail_service.proto",
}
